name: graphics_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.4
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  video_player: ^2.11.1
  video_player_win: ^3.2.2
  audioplayers: ^6.6.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/Hellobeanie/
    - assets/walkingBeanie/
    - assets/Worriedbeanie/
    - assets/Dancingcarrotino/
    - assets/Dancingtomathomas/
    - assets/Dancingbroccoli/
    - assets/Talkingbeanie/
    - assets/Worriedwave/
    - assets/Wavingcarrotino/
    - assets/Talkingcarrotino/
    - assets/Spinningbeanie/
    - assets/case2-screen/
    - assets/case10-dialogue1/dialogue1/
    - assets/case10-dialogue2/dialogue2/
    - assets/case10-dialogue3/dialogue3/
    - assets/case10-dialogue4/dialogue4/
    - assets/case10-dialogue5/dialogue5/
    - assets/case10-dialogue6/dialogue6/
    - assets/case10-dialogue7/dialogue7/
    - assets/case10-dialogue8/dialogue8/
    - assets/tutorialCase4-audios/
    - assets/tutorial3_screen-audios/
    - assets/tutorial10_screen-audios/
    - assets/tutorialCase8_screen-audios/
    - assets/sfx-audio/
    - assets/bg-audio/tutorial-music.mp3
    - assets/bg-audio/home-music.mp3
    - assets/about_tab/
  # Mystery Game Assets
    - assets/mystery/
    - assets/mystery/audio/
    - assets/mystery/audio/case1/backAlley/
    - assets/mystery/audio/case1/giovanni/
    - assets/mystery/audio/case1/loupe/
    - assets/mystery/audio/case1/municipal/
    - assets/mystery/audio/case1/pearlDistrict/
    - assets/mystery/audio/case1/police/
    - assets/mystery/audio/case1/viore/
    - assets/mystery/audio/case2/comlab/
    - assets/mystery/audio/case2/dean/
    - assets/mystery/audio/case2/guidance/
    - assets/mystery/audio/case2/gym/
    - assets/mystery/audio/case2/icto/
    - assets/mystery/audio/case2/it/
    - assets/mystery/audio/case3/bank/
    - assets/mystery/audio/case3/cell/
    - assets/mystery/audio/case3/cityPolice/
    - assets/mystery/audio/case3/cordova/
    - assets/mystery/audio/case3/hospital/
    - assets/mystery/audio/case3/huang/
    - assets/mystery/audio/case3/logistics/
    - assets/mystery/audio/case3/lowe/
    - assets/mystery/audio/case3/skyline/
    - assets/mystery/audio/case3/wasteCorp/
    - assets/mystery/character_profile/character_profile1/
    - assets/mystery/character_profile/character_profile2/
    - assets/mystery/character_profile/character_profile3/
    - assets/mystery/Case2/
    - assets/mystery/Case2/character_profile1/
    - assets/mystery/Case2/character_profile2/
    - assets/mystery/Case2/character_profile3/
    - assets/mystery/Case3/
    - assets/mystery/Case3/character_profile1/
    - assets/mystery/Case3/character_profile2/
    - assets/mystery/Case3/character_profile3/
    - assets/mystery/Case3/character_profile4/
    - assets/mystery/Case3/character_profile5/

  # Custom Fonts (Mystery Game)
  fonts:
    - family: Londrina Solid
      fonts:
        - asset: assets/mystery/fonts/LondrinaSolid-Black.ttf
        - asset: assets/mystery/fonts/LondrinaSolid-Light.ttf
        - asset: assets/mystery/fonts/LondrinaSolid-Regular.ttf
        - asset: assets/mystery/fonts/LondrinaSolid-Thin.ttf
    - family: Consolas
      fonts:
        - asset: assets/mystery/fonts/consolas.ttf
